### ISSUE TITLE
Cut and Paste

### ISSUE THREAD

**Issue by solleer** [Level-2/Transphporm#111]
Could a cut and paste functionality be added?

**Comment by solleer** [comment]
I am debating how useful this would be and if it would break any principles. The reason I thought about it is that good web practice is to have `script`s at the end of the file. But I want to have scripts in the files I throw in using template to then be at the bottom of the page. Tell me your thoughts.

**Comment by TomBZombie** [comment]
I'm not sure I understand what this would do, can you post some a sample template along with the proposed TSS and the output it would generate?

**Comment by TomBZombie** [comment]
Wouldn't it be better, in this case, to use:

```css
body {content-mode: append; content: template('scripts.xml'); 
```
which would have the scripts in their own file? That might be a problem when you have scripts that are unique to a page but then you could do:

```css
body {content-mode: append; content: template('scripttag.xml'); 

body > script {repeat: data(scripts); }
body  > script:attr(src) { content: data(url); }
```
