### ISSUE TITLE
How to check for value existence when populating a form?

### ISSUE THREAD

**Issue by cxj** [Level-2/Transphporm#121]
I have a login form with this TSS:
```css
#login input[name="username"]:attr(value) {
    content: data(username);
}
```
This is to populate the username field with whatever the user typed if they entered the wrong password or hit the login button and forgot to enter a password.  But it throws an error upon first time seeing the login form, because the value is empty (missing).

What's the right way to handle this?

**Comment by solleer** [comment]
Using this should work
```css
#login input[name="username"]:data[username]:attr(value) {
    content: data(username);
}
```
