### ISSUE TITLE
Parser\ValueData::callFuncOnObject() called with wrong first argument

### ISSUE THREAD

**Issue by cxj** [Level-2/Transphporm#129]
Method is clearly expecting something _other_ than my `$data` array as the first argument, yet it is receiving my array from my `$tpl->output($data)->body;` call.
```php

	private function callFuncOnObject($obj, $func, $args) {
		if (isset($obj->$func) && is_callable($obj->$func)) return call_user_func_array($obj->$func, $args);
		else return call_user_func_array([$obj, $func], $args);
	}
```

**Comment by cxj** [comment]
I added some debugging which logged argument types for all 3 arguments, and values for first argument.  Here's my log:
```
[21-Sep-2016 16:02:04 America/Chicago] callFuncOnObject obj: array
[21-Sep-2016 16:02:04 America/Chicago]  obj contains: Array
(
    [username] => testname
    [message] => Username and/or password not recognized.
)

[21-Sep-2016 16:02:04 America/Chicago] callFuncOnObject func: string
[21-Sep-2016 16:02:04 America/Chicago] callFuncOnObject args: array
```

**Comment by cxj** [comment]
This is using commit aa2fa24b68589b784b253c676128059d34ebcc89, which is most recent as of this writing, I think.

**Comment by TomBZombie** [comment]
Can you provide the XML and TSS?

**Comment by cxj** [comment]
XML:
```xml
<div class="login">

    <link href="/login.css" rel="stylesheet" type="text/css"/>

    <form id="login" action="/login" method="POST">

        <h1>
            <img src="/images/lynx-small.gif" alt="Dashboard"/>
        </h1>

        <input name="username" value="" placeholder="Username" type="text"
               required=""/>
        <input name="password" value="" placeholder="Password" type="password"
               required=""/>
        <button>Log In</button>

        <p class="error"></p>

    </form>

</div>
```

**Comment by cxj** [comment]
TSS:
```css
#login input[name="username"]:attr(value) {
    content: data(username);
}

#login p.error {
    content: data(message);
}

div.login:data[user.auth.isValid()=true] {
    content: "<p>dummy content from login.tss</p>";
    format: html;
}
```
