### ISSUE TITLE
How is date "relative" used in TSS file?

### ISSUE THREAD

**Issue by cxj** [Level-2/Transphporm#162]
How is the ["relative" date](https://github.com/Level-2/Transphporm/wiki/Locales#relative-times) feature described in the wiki used in a TSS file?  None of the syntax variations I've tried work.

**Comment by cxj** [comment]
I think I've figured it out.  At least, this seems to work:
```css
.web_last_logout {
    content: data(output.user_data.web_last_logout);
    format: relative;
}
```
