### ISSUE TITLE
Date format string strips escape characters?

### ISSUE THREAD

**Issue by cxj** [Level-2/Transphporm#163]
I'm trying to format my date-time string using the localization date string, as described [here in the wiki](https://github.com/Level-2/Transphporm/wiki/Locales#date-formats).  But the TSS processing seems to strip the backslashes out before the PHP `date()` or equivalent command is called to format the string.  Here's my TSS:
```css
.created {
    content: data(output.user_data.create_time);
    format: date "jS M Y \a\t h:s a";
}
```
Expected output:
`30th May 2017 at 10:52 am`
Actual output:
`30th May 2017 am31 10:52 am`
