### ISSUE TITLE
Regression between  319ec0fec6 and da7c375541

### ISSUE THREAD

**Issue by cxj** [Level-2/Transphporm#192]
I had been running on commit 319ec0fec6 and updated yesterday to da7c375541, and found part of my XML template no longer getting animated (content) by my TSS.  No errors were thrown.

I wrote a simple test case, but it works, so there's some side effect going on that's catalyzed by the larger template arrangement.  I'm building from partials, so it's fairly complex.  The basic TSS rule which is failing, however, is this:
```css
widget {
    content: template(attr(href));
    content-mode: replace;
}
```
Where it replaces any `<widget>` XML elements with the XML template file specified in that element's `href` attribute, for example:
```xml
<widget href="payer-picker.xml">this content should be replace</widget>
```

I will continue to pursue finding a simpler test case which reproduces the problem which is significantly smaller than my actual usage.  ;-)

**Comment by cxj** [comment]
In fact, that commit gives me a stack trace, although some number of commits later, the stack trace goes away and it just fails silently.  Here's the stack trace:
```
PHP Fatal error:  Uncaught Error: Call to undefined method DOMComment::getAttribute() in /Users/chris/test.templates/vendor/level-2/transphporm/src/Property/Content.php:91
Stack trace:
#0 /Users/chris/test.templates/vendor/level-2/transphporm/src/Property/Content.php(25): Transphporm\Property\Content->replaceContent(Object(DOMElement), Array)
#1 /Users/chris/test.templates/vendor/level-2/transphporm/src/Hook/PropertyHook.php(67): Transphporm\Property\Content->run(Array, Object(DOMElement), Array, Object(Transphporm\Hook\PseudoMatcher), Array)
#2 /Users/chris/test.templates/vendor/level-2/transphporm/src/Hook/PropertyHook.php(52): Transphporm\Hook\PropertyHook->callProperty('content', Object(DOMElement), Array)
#3 /Users/chris/test.templates/vendor/level-2/transphporm/src/Hook/PropertyHook.php(40): Transphporm\Hook\PropertyHook->callProperties(Object(DOMElement))
#4 /Users/chris/test.templates/vendor/level-2/transphporm/src/Template.php(70): Transphporm\Hook\PropertyHook->run(Object(DOMElement))
#5 /Users/chris/test.templates/v in /Users/chris/test.templates/vendor/level-2/transphporm/src/Property/Content.php on line 91
```

**Comment by cxj** [comment]
So, in oldest to newest order:
- b5a6278c97c23c3e468e66bc1cf27ca18a46b798 and earlier work correctly.
- a3c2e5ba331483c8d6d13873c261cfd12e2a2ff5 through 04a4d124f2d95e4a48a44ba4120974d6b80e2247 cause a stack trace.
- 1bb4b5dd2173dc344bcf66b4f5f9d7e0d91e6a52 through HEAD fail silently.

**Comment by cxj** [comment]
My primary TSS file:
```css
title {
    content: "My Title";
}

@import "navigation.tss";
nav {
    content: template("navigation.xml");
}

main {
    content: template("basic-elig-form.xml");
}

@import "widget/insert-widget.tss";

jslibs {
    content:
    "
<script src='/res/js/bootstrap-datepicker.min.js'></script>
    ";

    format: html;
    content-mode: replace;
}

#modal-right .modal-title {
    content: "Select a payer";
}
```

**Comment by cxj** [comment]
My primary XML file:
```xml
<!DOCTYPE html>
<html xml:lang="en" lang="en">
<head>
    <title>Default Title</title>
    <meta charset="utf-8"/>
    <meta http-equiv="x-ua-compatible" content="ie=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="/res/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="/res/css/bootstrap-theme.css"/>
</head>
<body>
<header class="container">
    <!-- Top bar -->
    <div class="row">
            <nav>
                <!-- actual navigation menus get placed here -->
            </nav>
    </div>
</header>
<main class="container">
    <!-- main content gets placed here -->
</main>
<footer class="footer">
    <p>
        <small>Copyright &#169; 1999 - 2018 My Company</small>
    </p>
</footer>
<script src="/res/js/jquery/jquery.min.js"></script>
<script src="/res/js/bootstrap.min.js"></script>
<jslibs>
    <!-- One or more JS libraries -->
</jslibs>
</body>
</html>
```

**Comment by cxj** [comment]
I still do not have a simple test to replicate the error.  The above primary files are just 2 of the 7 template files involved, included either via `@import` or `content: template();`.

**Comment by cxj** [comment]
Here's a demonstration test case.  This works with commit b5a6278c97c23c3e468e66bc1cf27ca18a46b798 and fails with all later commits:
```php
<?php
require "vendor/autoload.php";
$tss = '
main {
    content: template("basic-elig-form.xml");
}
@import "insert-widget.tss";
';
$xml = '
<!DOCTYPE html>
<html xml:lang="en" lang="en">
<head></head>
<body> <main>..main..</main> </body>
</html>
';
$tpl = new Transphporm\Builder($xml, $tss);
echo $tpl->output([])->body . PHP_EOL;
```

File `basic-elig-form.xml`:
```xml
<div class="basic-elig-form container-fluid">
    <widget href="payer-picker.xml">p1</widget>
</div>
```

File `insert-widget.tss`:
```css
widget {
    content: template(attr(href));
    content-mode: replace;
}
```

File `payer-picker.xml`:
```xml
<p> Just some proof text to show that the widget tag got replaced </p>
```
