### ISSUE TITLE
SCSS-style syntax?

### ISSUE THREAD

**Issue by garrettw** [Level-2/Transphporm#196]
Would it be possible to add at least some features from Sass' SCSS syntax, such as nested selectors? This could be useful for data looping (see #195).
Of course, this should not replace the current way of accomplishing the same thing, but rather add to it.

For reference, what I am asking for is this kind of thing:
```scss
.list {
  repeat: data();

  .item { // equivalent to: .list .item
    content: iteration();
  }

  .parent &::attr(id) { // equivalent to: .parent .list::attr(id)
    content: "special";
  }

  &.alternate { // equivalent to: .list.alternate
    content: "something else";
  }
}
```
