### ISSUE TITLE
[Feature Request] More :data[condition] selectors?

### ISSUE THREAD

**Issue by cxj** [Level-2/Transphporm#197]
Would it be possible and desirable to add a few more conditional operators to the `:data[condition]` selectors, possibly modeling the syntax on other CSS attribute selectors?  For example, I would find the following operations very helpful (chosen syntax is completely arbitrary and repurposed from CSS):

* Check whether data array is an empty array:
```css
div:data[myArray*=""] {display: none;}
```
* Check whether data array contains an element named `key1`:
```css
div:data[myArray^="key1"] {display: none;}
```
