### ISSUE TITLE
Conditional TSS treats floating point zero as blank

### ISSUE THREAD

**Issue by cj-clx** [Level-2/Transphporm#218]
It would be nice if the following worked as expect, displaying the value `$0.00` instead of leaving the XML unaltered.  
```php
<?php
require "vendor/autoload.php";

$xml = '<span>FAILS</span>';

$tss = 'span:[data(foo)!=""]  { content: "$", data(foo); } ';

$data['foo'] = 0.00;

$template = new Transphporm\Builder($xml, $tss);
echo $template->output($data)->body . PHP_EOL;
```
I have frequent need for this kind of check in my TSS code because the application service classes I'm calling don't always return every data element.

Is there perhaps a work-around I don't know about?

**Comment by garrettw** [comment]
That value would need to be a string in order to output the zeroes exactly as they are. A literal 0.00 is equivalent to 0.0 and 0 and similar to false and "".

**Comment by cj-clx** [comment]
My example above was perhaps a bit too limited.  The data value is a floating point number in my real application, and my TSS (with my current work-around) looks like this:
```css
/* Do not try to display missing values. */
td span.amount:[data(output.paid_amount)!=""] {
    content: "$", data(output.paid_amount);
    format: decimal 2;
}
/* DO display zero values. */
td span.amount:[data(output.paid_amount)=0] {
    content: "$", data(output.paid_amount);
    format: decimal 2;
}
```
