### ISSUE TITLE
content-mode: replace; content-mode: append

### ISSUE THREAD

**Issue by TomBZombie** [Level-2/Transphporm#23]
This is something that may be useful for bulding reusable parts e.g. includes and localisation Consider this: http://www.html5rocks.com/en/tutorials/webcomponents/imports/

We could implement this feature server side:

```html
<div>
<link rel="import" href="template.xml" />
</div>
```

```css
link[rel=import] {content: template(attr(href)); }
```

At the moment this will generate the following html:

```html
<div>
<link rel="import" href="template.xml">
...contents of template.xml...
</link>
</div>
```

Which is clearly not what we really want here. I'm going to add a `content-mode` property that lets you replace the entire matched element so using:

```css
link[rel=import] {content: template(attr(href)); content-mode: replace; }
```

will generate

```html
<div>
...contents of template.xml...
</div>
```

The problem with this, is that previously I suggested caching on a per rule basis. This will be impossible using the above, because the original node no longer exists. There's a couple of ways around this, but for now, content-mode would be useful.
