### ISSUE TITLE
White space sensitive, or other problem?

### ISSUE THREAD

**Issue by cxj** [Level-2/Transphporm#235]
This works, for setting an option in a `<select>` list:
```css
option[iteration(source_handle)=data(output.search.source_handle)] :attr(selected) {
   content: "selected";
}
```
But if I add a white space after the `option` element selector, it fails:
```css
option [iteration(source_handle)=data(output.search.source_handle)] :attr(selected) {
   content: "selected";
}
```

Am I overlooking something?
