### ISSUE TITLE
Binding data using object instead of array

### ISSUE THREAD

**Issue by tontof** [Level-2/Transphporm#24]
I was wondering if it's possible to use an object to populate a form using this kind of tss
```CSS
form {bind: data(object); }
form input[name]:attr(value) {content: data(attr(name))}
form textarea {content: data(attr(name));}
```
It works well if object is an associative array of course :-)
