### ISSUE TITLE
Content in templates

### ISSUE THREAD

**Issue by solleer** [Level-2/Transphporm#68]
I use this tss
```css
main { content: template('calendar.xml'); bind: data(model.getData()); }

head title, #pageTitle { content: "Events"; }

#calendar { content: data(cal_links.datetime); format: date "F Y"; }

@import '../../../Layouts/layout.tss';
```
cal_links.datetime formatted is March 2016
on this xml template
```xml
<!DOCTYPE html>
<html>
  <head>
    <title>Page Title</title>
    <meta charset="utf-8" />
    <!-- This allows the pages to scale well on mobile -->
    <meta name='viewport' content="width=device-width, initial-scale=1" />
    <base />
    <!-- Skeleton -->
    <link rel="stylesheet" href="css/skeleton/normalize.css" />
    <link rel="stylesheet" href="css/skeleton/skeleton.css" />
    <!-- jQuery -->
    <script src="js/jquery-1.11.3.js"></script>
    <script src="js/jquery.validate.js"></script>
    <!-- Custom -->
    <link rel="stylesheet" href="css/custom.css" />
    <!--<link rel="stylesheet" href=".css" />
		<script src=".js"></script>-->
    <script id="inline_js"></script>
  </head>
  <body>
    <div id='body_wrapper'>
      <header id='title'>
        <h1 class='container'>
          <div class='row'>
            <div class='two columns'>
            <img src='images/ElemukulekDuckLOGO2.png' class='u-max-full-width'/>
          </div>
          <div id='title_div' class='ten columns'>Elemukulek Chapter</div>
          </div>

        </h1>
      </header>
      <header id='menu' >
        <nav class='container'>
          <ul>
            <li data-link-type="home">
              <a href=" ">Home</a>
            </li>
            <li>
              <a href="officers">Officers</a>
            </li>
            <li>
              <a href="photos">Photos</a>
            </li>
            <li>
              <a href="publications">Publications</a>
            </li>
            <li data-link-type="events">
                <a href="events">Events</a>
            </li>
            <li>
              <a href="links">Links</a>
            </li>
          </ul>
        </nav>
      </header>
      <header id="messages">
        <div class="message type">
          <p>Message</p>
        </div>
      </header>
      <main class="container">

      </main>
      <footer>
        <div class="container">
          <a href="http://www.solleedevelopment.com">Created by Sollee Development</a>
          <a id="back_to_top" style='float: right;'>Back to Top</a>
        </div>
      </footer>
    </div>
    <!-- Wrapper div to help keep footer at bottom -->
  </body>
</html>
```
with this as calendar.xml
```xml
<div id="calendar">
<div id="calendar-title" class="row">
    <h2 class="title five columns">November 2015</h2><!-- style="padding-right: 30px; float: left; margin: 0.5ex 0;" -->
    <form class="controls calendar seven columns" method="get">
        <select name="month" id="month">
          <option value="1">January</option>
          <option value="2">February</option>
          <option value="3">March</option>
          <option value="4">April</option>
          <option value="5">May</option>
          <option value="6">June</option>
          <option value="7">July</option>
          <option value="8">August</option>
          <option value="9">September</option>
          <option value="10">October</option>
          <option value="11">November</option>
          <option value="12">December</option>
        </select>
        <select name="year" id="year">
          <option value="2015">2015</option>
        </select>
        <input name="submit" type="submit" value="Go" />
        <br />
      <a href="events/" class="previous">&lt;&lt; Previous Month</a> | <a href="events/" class="next">Next Month &gt;&gt;</a>
    </form>
</div>
<div style="overflow-x: auto;" class="row">
<table class="calendar">
  <thead >
    <tr class="calendar-row">
      <th class="calendar-day-head">Sunday</th>
      <th class="calendar-day-head">Monday</th>
      <th class="calendar-day-head">Tuesday</th>
      <th class="calendar-day-head">Wednesday</th>
      <th class="calendar-day-head">Thursday</th>
      <th class="calendar-day-head">Friday</th>
      <th class="calendar-day-head">Saturday</th>
    </tr>
  </thead>
  <tbody>
    <tr class="calendar-row">
      <td class="calendar-day">
        <div class="day-number">1</div>
        <div class="event">
          <a href="events/5">Event 5</a><!-- &#160; -->
        </div>
      </td>
    </tr>
  </tbody>
</table>
</div>
</div>
```
and the content is not changed

But when I use this tss
```css
main { content: template('calendar.xml'); bind: data(model.getData()); }

head title, #pageTitle { content: "Events"; }

main { content: data(cal_links.datetime); format: date "F Y"; }

@import '../../../Layouts/layout.tss';
```
the content of main is changed to `March 2016`

**Comment by TomBZombie** [comment]
This line is being run:

```css
main { content: data(cal_links.datetime); format: date "F Y"; }
```

Which is setting the `<main>` element to the date. It will override the content with this, if you want to append or prepend the date you'll need to use `:before` or `:after`

**Comment by TomBZombie** [comment]
I'm not sure what you're asking here, can you provide a minimal example with only the TSS rules that are needed for the includes and the ones that aren't working. 

```php
		$tss = '
		main { content: template("calendar.xml"); bind: data(model.getData()); }

		head title, #pageTitle { content: "Events"; }

		#calendar { content: data(); format: date "F Y" }

		';		


		$xml = '<main>test</main>';

		$tr = new \Transphporm\Builder($xml, $tss);

		file_put_contents('output.html', $tr->output(['model' => new Model])->body);

	}
	


class Model {
	public function getData() {
		return new \DateTime();
	}
}
```

the `#calendar` element's content is set to "March 2016".

**Comment by TomBZombie** [comment]
I've just added a `debug` format usable like this:

```
#div {content: data(whatever); format: debug;
```

This will put the contents of a `var_dump` of any object/array represented by `data(whatever)` into the selected element.

It might be useful for debugging here.

**Comment by solleer** [comment]
When I use the tss on the example above I get no print out
```css
main { content: template('calendar.xml'); bind: data(model.getData()); }

#calendar { content: data(); format: debug; }
```
When I use
```css
main { content: template('calendar.xml'); bind: data(model.getData()); }

main { content: data(); format: debug; }
```
It prints out all the data
