### ISSUE TITLE
function not returning value

### ISSUE THREAD

**Issue by solleer** [Level-2/Transphporm#70]
I run this tss
```css
main { bind: data(model.getData()); }
main {content: data(); format: debug;}
```
And the content is `NULL`
I have checked the function and the function is being called and returning a value correctly
