### ISSUE TITLE
Iteration and pseudo

### ISSUE THREAD

**Issue by solleer** [Level-2/Transphporm#71]
I have thiss tss
```css
#year option { repeat: data(year_select); }
#year option { content: iteration(year); }
#year option:attr(value) { content: iteration(year); }
```
The `#year option` sets the content right but `#year option:attr(value)` sets the value as an empty string
