### ISSUE TITLE
Nth-child when not same element type

### ISSUE THREAD

**Issue by solleer** [Level-2/Transphporm#85]
if you have this
xml
```xml
<h2 class="name">Test</h2>
<h3 class="name">Test</h3>
```
tss
```css
.event .name:nth-child(2) { display: none; }
```
The `<h3 class="name">Test</h3>` is not hidden

I am going to look into this
